name: Build and Deploy Android

on:
  push:
    branches:
      - feature/deploy-android
  workflow_call:

jobs:
  build_android:
    environment: homolog
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}

      - name: Get Version
        run: |
          app_build_number=$((${{ github.event.number }} + 80))
          app_build_name="2.0.1"
          echo "app_build_number=$app_build_number" >> $GITHUB_ENV

      - name: Setup Java Version
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter Version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.24.3"

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: Set envs
        run: |

      - name: Configure Keystore
        run: |
          echo "$ANDROID_PLAY_STORE_KEYSTORE_BASE64" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$ANDROID_KEYSTORE_KEY_ALIAS" >> key.properties
          echo "keyPassword=$ANDROID_KEYSTORE_KEY_PASSWORD" >> key.properties
          echo "storePassword=$ANDROID_KEYSTORE_STORE_PASSWORD" >> key.properties
        env:
          ANDROID_PLAY_STORE_KEYSTORE_BASE64: ${{ secrets.ANDROID_PLAY_STORE_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_KEY_ALIAS: ${{ vars.ANDROID_KEYSTORE_KEY_ALIAS }}
          ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      - name: Create .env file
        run: |
          echo "GRADS_URL=${{vars.API_COURSES}}" >> .env # The courses API
          echo "COURSES_URL=${{vars.API_SUBJECTS}}" >> .env # The subjects API
          echo "GRADE_OPTIMIZER_URL=${{vars.API_GRADE_OPTMIZER}}" >> .env # The grade optimizer API

      - name: Build Android
        run: |
          flutter build appbundle --release --build-name=2.0.1 --build-number=$app_build_number

      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: android/build/app/outputs/bundle/release/

  deploy_to_play_store:
    needs: build_android
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release.aab
          path: android/build/app/outputs/bundle/release/

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: Exec fastlane
        run: bundle exec fastlane homolog
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android
